name: Slack Notification

on: push
#on:
#  pull_request:
#    branches:
#      - master
#    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:



    - name: Get current date and time
      env: 
        TZ: "Asia/Tokyo" 
      id: date
      run: echo "::set-output name=date::$(date +'%s')"

    #- name: Get current date and time
    #  id: get-id
    #  run: |
    #    id=$(echo ${{github.event.repository.html_url}} | cut -d- -f2)
    #    echo "::set-output name=id::$id"

    #- name: check current date and time
    #  run: echo "${{steps.get-id.outputs.id}}" 


    - name: Send GitHub Action trigger data to Slack workflow 
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        payload: |
            {
              "text": "Pull request merged ${{ steps.comment-branch.outputs.head_ref }} by <https://github.com/${{ github.event.sender.login }}|${{ github.event.sender.login }}>",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "attachments": [
                {
                  "color": "good",
                  "fields": [
                    {
                      "value": "${{ github.event.pull_request.html_url }}"
                    }
                  ],
                  "footer": "${{ github.event.repository.html_url }}",
                  "ts": "${{ steps.date.outputs.date }}"
                }
              ]
            }

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
